# -*- coding: utf-8 -*-
"""ProjectEDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PYRzOK68qrQsOjdrVmSg1ZkwEA6t7gZv
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Load the data
from google.colab import files
uploaded = files.upload()

# Load the dataset
df = pd.read_csv("financial_aid_dataset.csv")

# --- 1. Descriptive Statistics ---
desc_stats = df.describe(include="all")

# --- 2. Visualize Key Feature Distributions ---
plt.figure(figsize=(14, 5))
plt.subplot(1, 3, 1)
sns.histplot(df["age"], kde=True, color="skyblue")
plt.title("Age Distribution")

plt.subplot(1, 3, 2)
sns.histplot(df["performance_score"], kde=True, color="orange")
plt.title("Performance Score Distribution")

plt.subplot(1, 3, 3)
sns.countplot(data=df, x="household_income_bracket", palette="Set2")
plt.title("Income Bracket Distribution")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# --- 3. Correlation Heatmap ---
numeric_df = df.select_dtypes(include=["float64", "int64"])
plt.figure(figsize=(8, 6))
sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

# --- 4. Feature Engineering ---
df["fee_to_income_ratio"] = df["study_hours"] / (df["dependents"] + 1)
df["gpa_trend"] = df["performance_score"] / df["study_hours"]
engineered_preview = df[["study_hours", "dependents", "fee_to_income_ratio", "gpa_trend"]].head()

# --- 5. Document Insights ---
insights = {
    "Most common income bracket": df["household_income_bracket"].mode()[0],
    "Average performance score": round(df["performance_score"].mean(), 2),
    "Average attendance rate": round(df["attendance"].mean(), 2),
    "Highest correlated features": numeric_df.corr().abs().unstack().sort_values(ascending=False).drop_duplicates().head(5)
}

desc_stats, engineered_preview, insights

